numbers = list(map(lambda x: x, input().split(', ')))
positive = list(filter(lambda x: int(x) >= 0, numbers))
positive = ', '.join(positive)
negative = list(filter(lambda x: int(x) < 0, numbers))
negative = ', '.join(negative)
even = list(filter(lambda x: int(x) % 2 == 0, numbers))
even = ', '.join(even)
odd = list(filter(lambda x: not int(x) % 2 == 0, numbers))
odd = ', '.join(odd)
print(f'Positive: {positive}\nNegative: {negative}\nEven: {even}\nOdd: {odd}')
